# Generated by Django 2.2.16 on 2022-05-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220511_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
