# Generated by Django 2.2.16 on 2022-05-15 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20220512_1444'),
        ('users', '0008_merge_20220512_1347'),
    ]

    operations = [
    ]
