# Generated by Django 2.2.19 on 2022-05-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220516_2336'),
        ('reviews', '0002_auto_20220517_1014'),
    ]

    operations = [
    ]
