# Generated by Django 2.2.16 on 2022-05-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220512_1146'),
        ('reviews', '0004_auto_20220511_1306'),
    ]

    operations = [
    ]
